### ISSUE TITLE
请教下如何通过支付宝的那个类似方法启动微博个人主页？

### ISSUE THREAD

**Issue by umeitime** [Bakumon/UGank#2]
请教下如何通过支付宝的那个类似方法启动微博个人主页？
在我的APP打开微博某个人的个人主页。

**Comment by Bakumon** [comment]
支付宝能打开到支付界面是因为支付宝提供了 `Intent scheme URI` 打开方式
```java
Intent intent = Intent.parseUri(intentFullUrl, Intent.URI_INTENT_SCHEME);
```

可以看[这里](http://blog.feng.moe/2016/08/29/alipay-zerosdk/)

微博要想实现打开某个 Activity，需要满足以下任意一个
1. 该 Activity 有没有提供给别的应用打开的 `intent-filter`
2. 应用提供了 `Intent scheme URI` 类型的 `intent-filter`

**Comment by Bakumon** [comment]
刚才试了一下打开微博界面，虽然有 `intent-filter` ，但是没有权限，还是打不开
